---
driver:
  name: vagrant
  ssh:
    insert_key: false
  customize:
    cpus: 1
    memory: 1024

provisioner:
  name: chef_zero
  chef_client_path: /usr/bin/chef-client
  require_chef_omnibus: 12.14.89

transport:
  name: sftp

platforms:
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.6
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[simple-logstash-test]
    attributes:

