---
driver:
  name: dokken
  chef_version: 13.5.3
  privileged: true

provisioner:
  name: dokken
  # chef_log_level: info

transport:
  name: dokken

verifier:
  name: inspec
  # output: reports/%{platform}_%{suite}_inspec.xml

platforms:
  - name: debian-8
    driver:
      image: dokken/debian-8
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt]
    attributes:
      java:
        jdk_version: 7

  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt]

  - name: ubuntu-16
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt]

  - name: ubuntu-14
    driver:
      image: dokken/ubuntu-14.04
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt]

  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd
    run_list:
      - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[simple-logstash-test]
