---
driver:
  name: dokken
  chef_version: 14
  privileged: true

provisioner:
  name: dokken
  # chef_log_level: info

transport:
  name: dokken

verifier:
  name: inspec
  reporter:
    - junit:reports/%{platform}_%{suite}_inspec.xml
    - documentation

platforms:
  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt]

  - name: ubuntu-16
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt]

  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd
    run_list:
      - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[simple-logstash-test]
    attributes:
      logstash:
        download_url: http://nexus.e3s.epam.com/repository/e3s-install/logstash/6.2.3/logstash-6.2.3.tar.gz

  - name: runit
    run_list:
      - recipe[simple-logstash-test::runit]
    attributes:
      logstash:
        download_url: http://nexus.e3s.epam.com/repository/e3s-install/logstash/6.2.3/logstash-6.2.3.tar.gz
