---
driver:
  name: docker
  provision_command:
    # Modern chef includes ruby 2.3.1 which we're want to see
    - curl -L https://www.opscode.com/chef/install.sh | bash -s -- -v 12.14.89
    # For auto tests we need additional gems which requires build tools (example:)
    - apt-get -f -y install build-essential libxml2 libxml2-dev libxml2-utils

provisioner:
  name: chef_zero
  required_chef_omnibus: false

platforms:
  - name: debian-wheezy
    driver_config:
      run_command: /sbin/init

  - name: debian-jessie
    driver_config:
      run_command: /bin/systemd

  - name: centos-6.7
  - name: centos-7.2
  - name: ubuntu-12.04
  - name: ubuntu-14.04
