AllCops:
  TargetRubyVersion: 2.3
  DefaultFormatter: fuubar
  DisplayCopNames: true

Encoding:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

NumericLiterals:
  Enabled: false

HashSyntax:
  Enabled: false

RescueModifier:
  Enabled: false

Metrics/AbcSize:
  Max: 60

Style/Documentation:
  Enabled: false
